apiVersion: v1
kind: Service
metadata:
  name: my-actix-loadbalancer
spec:
  selector:
    app: my_actix_app
  ports:
    - port: 30005          # How other machines will access
      targetPort: 5031     # Port you want to expose
  type: LoadBalancer
