# copy pasted practically straight from ChatGPT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my_actix_app
  template:
    metadata:
      labels:
        app: my_actix_app
    spec:
      containers:
        - name: actix-1-container
          image: chilinbrian/actix_1_image:latest
          ports:
            - containerPort: 5031
          imagePullPolicy: Always
