kind: Service
apiVersion: v1
metadata:
  name: external-dynmap
spec:
  ports:
  - protocol: TCP
    port: 80

---

kind: Endpoints
apiVersion: v1
metadata:
  name: external-dynmap
subsets:
- addresses:
  - ip: 192.168.1.69
  ports:
  - port: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: external-ingress
spec:
  rules:
  - host: dynmap.brian2002.com
    http:
      paths:
      - backend:
          serviceName: external-dynmap
          servicePort: 80
