apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - cidr: 10.244.0.0/16    # Must match kubeadm init --pod-network-cidr
      encapsulation: VXLAN
      natOutgoing: Enabled
      nodeSelector: all()
